In [1]:
import numpy as np

arr = np.arange(5)

print(arr)    # Output: [0 1 2 3 4]

[0 1 2 3 4]


In [ ]:
arr = np.arange(start=1, stop=20, step=3)

print(arr)   # Output: [1  4  7 10 13 16 19]

[ 1  4  7 10 13 16 19]


In [5]:
years = np.arange(start=1986, stop=3000, step=75)

print(years)  # Output: [1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]

[1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]
